version: "3"

services:
  postgres:
    container_name: epns_postgres
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ../db/postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  web:
    container_name: epns_web
    restart: always
    image: epns_web
    build: .
    command: >
      sh -c "python wait_for_postgres.py &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_CONFIGURATION=Production
    volumes:
      - ./:/code
      - ./static:/static
    expose:
      - "8000"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
