# Generated by Django 3.2.5 on 2021-07-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
                ('recipient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlackModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackURl', models.URLField()),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamsURl', models.URLField()),
                ('message_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(max_length=100)),
                ('telegram_chatID', models.CharField(max_length=10)),
                ('message_content', models.TextField()),
            ],
        ),
    ]
