# Generated by Django 3.2.5 on 2021-07-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210726_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlookmodel',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='slackmodel',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='teamsmodel',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='telegrammodel',
            old_name='message_content',
            new_name='message',
        ),
    ]
